<?php

// app/Console/Commands/GenerateRouteTypes.php
namespace App\Console\Commands;

use Illuminate\Console\Command;
use Tighten\Ziggy\Ziggy;

class GenerateRouteTypes extends Command
{
  protected $signature = 'generate:route-types';
  protected $description = 'Generate TypeScript definitions for Laravel routes';

  public function handle()
  {
    $ziggy = (new Ziggy)->toArray();
    $routes = $ziggy['routes'];

    $types = "// Auto-generated by Laravel - DO NOT EDIT MANUALLY\n";
    $types .= "declare module '@custom-types/ziggy-js' {\n";
    $types .= " interface RouteList {\n";

    foreach ($routes as $name => $route) {
      $params = empty($route['parameters'])
        ? '{params: {_query?: Record<string, string | number>}}'
        : sprintf(
          '{params: { %s, _query?: Record<string, string | number> } }',
          collect($route['parameters'])
            ->map(fn($param) => "{$param}?: string | number")
            ->join(', ')
        );

      $types .= " '{$name}': {$params};\n";
    }

    $types .= " }\n";
    $types .= "}\n";

    // Ensure directory exists
    if (!is_dir($dir = resource_path('js/types'))) {
      mkdir($dir, 0755, true);
    }

    file_put_contents(resource_path('js/types/ziggy.d.ts'), $types);

    $this->info('TypeScript route definitions generated successfully!');
  }
}