// Auto-generated by Laravel - DO NOT EDIT MANUALLY
declare module '@custom-types/ziggy-js' {
    interface RouteList {
        'sanctum.csrf-cookie': { params: { _query?: Record<string, string | number> } };
        home: { params: { _query?: Record<string, string | number> } };
        about: { params: { _query?: Record<string, string | number> } };
        dashboard: { params: { _query?: Record<string, string | number> } };
        'blog.index': { params: { _query?: Record<string, string | number> } };
        'blog.create': { params: { _query?: Record<string, string | number> } };
        'blog.edit': { params: { post?: string | number; _query?: Record<string, string | number> } };
        'blog.show': { params: { post?: string | number; _query?: Record<string, string | number> } };
        'blog.store': { params: { _query?: Record<string, string | number> } };
        'blog.destroy': { params: { post?: string | number; _query?: Record<string, string | number> } };
        'blog.update': { params: { post?: string | number; _query?: Record<string, string | number> } };
        'blog.comments.store': { params: { post?: string | number; _query?: Record<string, string | number> } };
        'blog.vote': { params: { post?: string | number; _query?: Record<string, string | number> } };
        'blog.comments.vote': { params: { post?: string | number; comment?: string | number; _query?: Record<string, string | number> } };
        'profile.edit': { params: { _query?: Record<string, string | number> } };
        'profile.update': { params: { _query?: Record<string, string | number> } };
        'profile.destroy': { params: { _query?: Record<string, string | number> } };
        'password.edit': { params: { _query?: Record<string, string | number> } };
        'password.update': { params: { _query?: Record<string, string | number> } };
        appearance: { params: { _query?: Record<string, string | number> } };
        register: { params: { _query?: Record<string, string | number> } };
        login: { params: { _query?: Record<string, string | number> } };
        logout: { params: { _query?: Record<string, string | number> } };
        'storage.local': { params: { path?: string | number; _query?: Record<string, string | number> } };
    }
}
