// Auto-generated by Laravel - DO NOT EDIT MANUALLY
declare module '@custom-types/ziggy-js' {
    interface RouteList {
        'sanctum.csrf-cookie': never;
        home: never;
        dashboard: never;
        'blog.index': never;
        'blog.create': never;
        'blog.edit': { params: { post?: string | number } };
        'blog.show': { params: { post?: string | number } };
        'blog.store': never;
        'blog.destroy': { params: { post?: string | number } };
        'blog.update': { params: { post?: string | number } };
        'blog.comments.store': { params: { post?: string | number } };
        'blog.vote': { params: { post?: string | number } };
        'blog.comments.vote': { params: { post?: string | number; comment?: string | number } };
        'profile.edit': never;
        'profile.update': never;
        'profile.destroy': never;
        'password.edit': never;
        'password.update': never;
        appearance: never;
        register: never;
        login: never;
        logout: never;
        'storage.local': { params: { path?: string | number } };
    }
}
